### ISSUE TITLE
Error Messages when executing tool.

### ISSUE THREAD

**Issue by dfirresearch** [NetSPI/NetblockTool#1]
[*] Retrieving networks using Google Dorking for facebook (usually < 30 pages)
Traceback (most recent call last):
  File "NetblockTool.py", line 1725, in get_google_networks
    network = str(netaddr.IPNetwork(tag.text.split(' ')[0]))
AttributeError: module 'netaddr' has no attribute 'IPNetwork'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NetblockTool.py", line 2033, in <module>
    results = main(arg_target, arg_company_name, query, arg_verbose, arg_threshold, arg_geo, arg_address, arg_address_grep, arg_version, arg_quiet, arg_poc, arg_no_google)
  File "NetblockTool.py", line 164, in main
    google_networks = get_google_networks(target, verbose, quiet)
  File "NetblockTool.py", line 1744, in get_google_networks
    except netaddr.AddrFormatError:
AttributeError: module 'netaddr' has no attribute 'AddrFormatError'

**Comment by venominfosec** [comment]
What version of netaddr is installed?
